// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcfUiFDwAkKMiF8Lr7oUtMC8CzRV4Euxc',
    appId: '1:948018919748:web:3d0f1f15f177be34de3f11',
    messagingSenderId: '948018919748',
    projectId: 'yhal-f96b9',
    authDomain: 'yhal-f96b9.firebaseapp.com',
    storageBucket: 'yhal-f96b9.firebasestorage.app',
    measurementId: 'G-XLWLDPTFLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-7MMGcC6GepAhu59z30be8anSdJRhOFw',
    appId: '1:948018919748:android:c859246eecc9edbade3f11',
    messagingSenderId: '948018919748',
    projectId: 'yhal-f96b9',
    storageBucket: 'yhal-f96b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCukeZrrvXfT6Pr0_jANfqJjLoXoXGmX5c',
    appId: '1:948018919748:ios:287ecf7dbd1229eede3f11',
    messagingSenderId: '948018919748',
    projectId: 'yhal-f96b9',
    storageBucket: 'yhal-f96b9.firebasestorage.app',
    iosClientId:
        '948018919748-e2bce7snv7u23v7auot5rj7jmrsbqc9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.yhalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCukeZrrvXfT6Pr0_jANfqJjLoXoXGmX5c',
    appId: '1:948018919748:ios:287ecf7dbd1229eede3f11',
    messagingSenderId: '948018919748',
    projectId: 'yhal-f96b9',
    storageBucket: 'yhal-f96b9.firebasestorage.app',
    iosClientId:
        '948018919748-e2bce7snv7u23v7auot5rj7jmrsbqc9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.yhalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcfUiFDwAkKMiF8Lr7oUtMC8CzRV4Euxc',
    appId: '1:948018919748:web:facfcd9f983b2cebde3f11',
    messagingSenderId: '948018919748',
    projectId: 'yhal-f96b9',
    authDomain: 'yhal-f96b9.firebaseapp.com',
    storageBucket: 'yhal-f96b9.firebasestorage.app',
    measurementId: 'G-QCC0HMN7NM',
  );
}
