// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC77xyjWITVIy8qgAdkJ--soohJIA95Bc',
    appId: '1:426678815225:web:80f569ac02c31f70afd528',
    messagingSenderId: '426678815225',
    projectId: 'yhla-staging',
    authDomain: 'yhla-staging.firebaseapp.com',
    storageBucket: 'yhla-staging.firebasestorage.app',
    measurementId: 'G-N1G1HFVKZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZQmyfoS35D968GFXf7MSfotlukmG-u0',
    appId: '1:426678815225:android:5a90d958da5ad10cafd528',
    messagingSenderId: '426678815225',
    projectId: 'yhla-staging',
    storageBucket: 'yhla-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVpWx9UyNMuwyfkH0o5I-SoBDAMWpwaME',
    appId: '1:426678815225:ios:704a9c255f09aa17afd528',
    messagingSenderId: '426678815225',
    projectId: 'yhla-staging',
    storageBucket: 'yhla-staging.firebasestorage.app',
    iosClientId:
        '426678815225-72ns930md3h5udop0fiqhmke2jkluki0.apps.googleusercontent.com',
    iosBundleId: 'com.example.yhalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVpWx9UyNMuwyfkH0o5I-SoBDAMWpwaME',
    appId: '1:426678815225:ios:704a9c255f09aa17afd528',
    messagingSenderId: '426678815225',
    projectId: 'yhla-staging',
    storageBucket: 'yhla-staging.firebasestorage.app',
    iosClientId:
        '426678815225-72ns930md3h5udop0fiqhmke2jkluki0.apps.googleusercontent.com',
    iosBundleId: 'com.example.yhalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC77xyjWITVIy8qgAdkJ--soohJIA95Bc',
    appId: '1:426678815225:web:0af13416acabe0c6afd528',
    messagingSenderId: '426678815225',
    projectId: 'yhla-staging',
    authDomain: 'yhla-staging.firebaseapp.com',
    storageBucket: 'yhla-staging.firebasestorage.app',
    measurementId: 'G-DT2SCGCE47',
  );
}
